version: '3.8'

services:
  unbsign-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unbsign-api
    ports:
      - "8080:8080"
    volumes:
      - ./sign/keystore:/app/keystore
    networks:
      - unbsign-webapp_unbsign-network
    environment:
      - TZ=America/Sao_Paulo

networks:
  unbsign-webapp_unbsign-network:
    external: true